apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-app
spec:
  selector:
    matchLabels:
      app: qrcode-app
  replicas: 2
  template:
    metadata:
      labels:
        app: qrcode-app
    spec:
      containers:
      - name: myapp
        image: mohamedcloud/qr_code_app:v3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: qrcode-app-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: db-password
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
        ports:  
          - name: http
            containerPort: 8080
            protocol: TCP
            
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5


