apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qrcode-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shehab-19/Depi_graduation_project.git
    targetRevision: HEAD
    path: QRCode_APP_Chart
    helm:
      parameters:
        - name: Secret.DB_PASSWORD
          value: $DB_PASSWORD
          forceString: true
        - name: Secret.DB_HOST
          value: $DB_HOST  
          forceString: true
        - name: Secret.DB_NAME
          value: $DB_NAME
          forceString: true
        - name: Secret.DB_USER
          value: $DB_USER
          forceString: true
        - name: Ingress.HostName
          value: $URL
          forceString: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true