kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 90
        protocol: TCP
      # - containerPort: 443
      #   hostPort: 443
      #   protocol: TCP