{{- with .Values.Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .SecretName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: generic
data:
  db-password: {{ .DB_PASSWORD | b64enc }} 
  db-host: {{ .DB_HOST | b64enc }}
  db-name: {{ .DB_NAME | b64enc }}
  db-user: {{ .DB_USER | b64enc}}
{{- end }}
